"""Add produk column to pesanan table

Revision ID: 30bf46007e73
Revises: 
Create Date: 2025-01-21 15:21:04.155971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bf46007e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pesanan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produk', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('harga', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_harga', sa.Float(), nullable=True))
        batch_op.alter_column('nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('tanggal',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('jumlah',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pesan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pesanan', schema=None) as batch_op:
        batch_op.alter_column('pesan',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('jumlah',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tanggal',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('total_harga')
        batch_op.drop_column('harga')
        batch_op.drop_column('produk')

    # ### end Alembic commands ###
